[package]
name = "frets"
version = "0.1.0"
edition = "2021"
description = "Notation Toolbox"

[package.metadata.bundle]
identifier = "fun.notation.toolbox"
resources = ["assets"]

[features]
default = [
]

native = [
]

[dependencies]
fretboard = { path = "../../views/fretboard" }